f_name=input("Enter your First Name= ")
l_name=input("Enter your Last Name= ")
course=input('Enter your Course=')
batch=input('Enter your Batch=')
sec=input('Enter your Sec=')
print('\n\n\t\'BioData\'\n\t--------------\nYour Full Name is',f_name.rstrip().title(),l_name.lstrip().capitalize())
print('Your Course is:', course.title())
print('Your Batch is:',batch.upper())
print('Your Section is',sec.capitalize())