print ("\t\tStudent BioData Form")
name = (input("Enter Student Name: "))
dob = (input ("Enter Date of Birth(DD/MM/YYYY): "))
roll = (input ("Roll No: "))
section = (input ("Section: "))
percentage =(input ("Percentage: "))
matric = (input("Grade in Matriculation: ")) 
inter = (input("Grade in Intermediate: "))
print ("Enter Student Name:" ,name)
print ("Enter Date of Birth:" ,dob)
print ("Roll No:" , roll)
print ("Section:" , section)
print ("Percentage:" , percentage)
print ("Grade in Matriculation:" , matric)
print ("rade in Intermediate:" , inter)
print(name , dob , roll , section , percentage , sep="\n")