a = int(input("Enter MATHS Marks: "))
b = int(input("Enter ENG Marks: "))
c = int(input("Enter SCIENCE Marks: "))
d = int(input("Enter SST Marks: "))
e = int(input("Enter URDU Marks: "))
print("\n\n\t\t\t" "MarkSheet")
print("Maths Marks", a, "/50")
print("English Marks", b,"/50")
print("Science Marks", c,"/50")
print("SSt Marks", d,"/50")
print("Urdu Marks", e,"/50""\n")
Total_Marks = sum([a, b, c, d, e])
print("\t\t""Total Marks: " ,Total_Marks, "/250")
print("\t\t""Average: ", Total_Marks/5)
print("\t\t""Percenatage",Total_Marks/250*100 ,"%")