print ("\n\t\tStudent BioData Form")
name = (input("\nEnter Patient's Name: "))
dob = (input ("Enter Date of Birth(DD/MM/YYYY): "))
nic = (input ("CNIC No: "))
f_name = (input ("Father's Name: "))
gender =(input ("Gender: "))
height = (input("Height: ")) 
weight = (input("Weight: "))
bmi = (input("BMI: "))
m_s= (input("Martial Status: "))
print ("Enter Patient's Name:" ,name)
print ("Enter Date of Birth:" ,dob)
print ("CNIC No: " , nic)
print ("Father's Name:" , f_name)
print ("Gender:" , gender)
print ("Height:" , height)
print ("Weight:" , weight)
print(name , dob , roll , section , percentage , sep="\n")